version: 1.0.{build}
os: Visual Studio 2015
build:
  verbosity: minimal
environment:
  COVERALLS_REPO_TOKEN:
    secure: /CfucRi5JIhmrcPoornr8fG/r+sRY4jETLdQqJlbxo/4rMMtfuKYI2TDeNu9gg+A
build_script:
- dotnet restore
- dotnet pack -c Release -o Output src\HtmlMinificationMiddleware\ 

artifacts:
- path: '\Output\*.nupkg'
  name: Nuget Deploy
deploy:
- provider: NuGet
  server: nuget.org
  api_key:
    secure: 5XsCPhzHSChTdym1nwcZps3YxhZqySNztlUeT1rWtMmvrDM+R+WzxUkrYiMLBUVs
    skip_symbols: true
