version: 2.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal
environment:
  COVERALLS_REPO_TOKEN:
    secure: /CfucRi5JIhmrcPoornr8fG/r+sRY4jETLdQqJlbxo/4rMMtfuKYI2TDeNu9gg+A
build_script:
- dotnet restore src\HtmlMinificationMiddleware\HtmlMinificationMiddleware.csproj 
- dotnet pack -c Release -o Output src\HtmlMinificationMiddleWware\HtmlMinificationMiddleware.csproj 
- dotnet restore Test\HtmlMinificationMiddlewareTests\HtmlMinificationMiddleware.Tests.csproj 
test_script:
- cmd: C:\Users\appveyor\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test C:\projects\HtmlMinificationMiddleware\Test\HtmlMinificationMiddlewareTests\HtmlMinificationMiddleware.Tests.csproj" -register:user -filter:"+[*]* -[xunit*]*" -output:coverage.xml -oldStyle
after_test:		
- cmd: C:\Users\appveyor\.nuget\packages\coveralls.io\1.3.4\tools\coveralls.net.exe --opencover coverage.xml --full-sources
artifacts:
- path: '\Output\*.nupkg'
  name: Nuget Deploy
deploy:
- provider: NuGet
  server: nuget.org
  api_key:
    secure: 5XsCPhzHSChTdym1nwcZps3YxhZqySNztlUeT1rWtMmvrDM+R+WzxUkrYiMLBUVs
    skip_symbols: true
