version: 1.0.{build}
os: Visual Studio 2015
environment:
  COVERALLS_REPO_TOKEN:
    secure: /CfucRi5JIhmrcPoornr8fG/r+sRY4jETLdQqJlbxo/4rMMtfuKYI2TDeNu9gg+A
build_script:
- dnvm upgrade
- dnu restore
- dnu build src\HtmlMinificationMiddleware\
after_build:
- cmd: dnu pack src\HtmlMinificationMiddleware --configuration Release --out Output
test_script:
- cmd: C:\Users\appveyor\.dnx\packages\OpenCover\4.6.261-rc\tools\OpenCover.Console.exe -target:"C:\Users\appveyor\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\dnx.exe" -targetargs:"--lib C:\projects\HtmlMinificationMiddleware\src\HtmlMinificationMiddleware\bin\Debug\dnx451 -p C:\projects\HtmlMinificationMiddleware\test\HtmlMinificationMiddlewareTests test -parallel none" -output:coverage.xml -register:user -filter:"+[*]* -[xunit*]*"
after_test:
- cmd: C:\Users\appveyor\.dnx\packages\coveralls.io\1.3.4\tools\coveralls.net.exe --opencover coverage.xml --full-sources
- cmd: dnu pack src\HtmlMinificationMiddleware --configuration Release --out Output

artifacts:
- path: '\Output\Release\**\*.nupkg'
  name: Nuget Deploy
deploy:
- provider: NuGet
  server: nuget.org
  api_key:
    secure: 5XsCPhzHSChTdym1nwcZps3YxhZqySNztlUeT1rWtMmvrDM+R+WzxUkrYiMLBUVs
    skip_symbols: true
